[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal/v3'

baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'den of saltyeyes'
theme = 'terminal'

[params]
	fullWidthTheme = false
	centerTheme = false

	[languages]
		[languages.en]
			title = "den of saltyeyes"
			subtitle = "things and stuff"
			keywords = ""
			copyright = ""
			menuMore = "Show more"
			readMore = "Read more"
			readOtherPosts = "Read other posts"

		[languages.en.params.logo]
			logoText = "den of saltyeyes"
			logoHomeLink = "/"
